### ISSUE TITLE
Field not showing

### ISSUE THREAD

**Issue by rebornmedia1** [tv2regionerne/statamic-image-cropper#1]
I have just installed on 3.4.7. I can create the blue print fine but when I go to edit the entry there is no field. 

Error in console log

TypeError: Cannot read properties of undefined (reading 'data')
 at a.source (addon-3efe6eb0.js:10:38560)
    at fn.get (vue.common.prod.js:6:26596)
    at fn.evaluate (vue.common.prod.js:6:27746)
    at a.source (vue.common.prod.js:6:29650)
    at a.<anonymous> (vue.common.prod.js:6:26428)
    at fn.get (vue.common.prod.js:6:26596)
    at new fn (vue.common.prod.js:6:26514)
    at e.$watch (vue.common.prod.js:6:33210)
    at _n (vue.common.prod.js:6:29834)
    at vue.common.prod.js:6:29301
qe @ vue.common.prod.js:6

**Comment by rebornmedia1** [comment]
This was user error. My handle wasn't matching my source field.

**Comment by sylvesterdamgaard** [comment]
@FrittenKeeZ Should we add some better error handling on the handle mismatch?

**Comment by rebornmedia1** [comment]
that might be useful. My issue was I thought it was a field type in itself, not that it needed linking with an existing one. 

Fantastic addon by the way! No w I have it working it is brilliant.

**Comment by sylvesterdamgaard** [comment]
@rebornmedia1 I'm happy you find it useful. :)
It's the first quick release, so there's room for some improvements here and there.

**Comment by FrittenKeeZ** [comment]
@rebornmedia1 we just released v0.3.0 with better error handling and more feature, so check it out :)
