### ISSUE TITLE
Misspelling and Pixel Dimensions

### ISSUE THREAD

**Issue by GreatGrady** [tv2regionerne/statamic-image-cropper#4]
There is a misspelling here: "Wheher to use manual, collection or taxonomy based dimensions."

On another note, I want my clients to have the ability to crop to exact pixel dimensions (e.g. 622px w x 348px h). Can you provide this option?

**Comment by minemindmedia** [comment]
I am only here because I can't get the crop to display on the front-end at all....
BUT there is a freeform option you can use to choose the exact dimensions.

**Comment by GreatGrady** [comment]
Freeform is not a good solution for me because I want he ability to force clients to crop at a certain size. I would like a dimension option that looks something like this:

dimensions:
'622_348': Exact

Then when the client chooses to crop the image it will crop the image to exactly 622px x 348px. The Freeform option gives too much freedom to the client to make a mistake in cropping the image. 

Hopefully the author can help you with your front-end issue. I have not got that far yet. I am hoping the author will add this dimensions option.

**Comment by minemindmedia** [comment]
Yeah, it would make sense to be able to specify the crop size in the control panel / YAML file.

The front-end issue is weird, not sure why it's not working. Last update to this was 10/5, so I'd assume it would be working.

**Comment by minemindmedia** [comment]
Hey @GreatGrady 

Not sure if this is a solution to your problem, but it's going to work well for me:
https://statamic.dev/image-manipulation

It will allow for you to set defined image sizes and use the glide tag to reference a specific preset.
Furthermore, it appears you can pass those presets onto an assets container to choose from when adding an image.

**Comment by GreatGrady** [comment]
Thanks @minemindmedia! I think that might work.
