### ISSUE TITLE
Cropped version not displaying on front-end

### ISSUE THREAD

**Issue by minemindmedia** [tv2regionerne/statamic-image-cropper#5]
In the CP, I am able to use the cropping feature:

![image](https://github.com/tv2regionerne/statamic-image-cropper/assets/8854361/93ac0e98-47a4-40f3-83e2-314b53b5282b)

I then save the the cropped image and publish.

Both of these produce a non-cropped image on the front-end:

```
<img src="{{ image:url }}" alt="{{ image:alt }}">
<img src="{{ glide:image :crop="crops:16_1:crop" }}" />
```

**Comment by sylvesterdamgaard** [comment]
The cropping should work if you have a the crop configured with the key "16_1" like in the image below.
Can you display the configuration of the cropper fieldtype?

![image](https://github.com/tv2regionerne/statamic-image-cropper/assets/2431914/56bd9859-1a00-4d5f-9674-0f29422944ad)

**Comment by beliven-fabrizio-gortani** [comment]
I've the same problem. I've declared `16_9` and `freeform` dimensions and inside the control panel the field work as expected, but in the frontend it doesn't work.

In the CP I've following situation:

<img width="1378" alt="image" src="https://github.com/tv2regionerne/statamic-image-cropper/assets/99825015/aab1a6fb-949d-4acf-9229-bab0f56f6b72">


and in the frontend this one:


<img width="606" alt="image" src="https://github.com/tv2regionerne/statamic-image-cropper/assets/99825015/d78498f2-d1dd-48bc-b30c-37f4ee278659">

In the screen you can see the crop is ignored

Below the code used in FE:

```html
<img src="{{ glide:immagine_card :crop="crops:freeform:crop" }}"  alt="{{ immagine_card:alt }}"  />
```
Of course I've set the dimension `freeform` in the field section:

<img width="877" alt="image" src="https://github.com/tv2regionerne/statamic-image-cropper/assets/99825015/d066d5bb-5012-49d8-ad3e-b4dcaaaf8a59">

**Comment by sylvesterdamgaard** [comment]
> I've the same problem. I've declared `16_9` and `freeform` dimensions and inside the control panel the field work as expected, but in the frontend it doesn't work.
> 
> In the CP I've following situation:
> 
> <img alt="image" width="1378" src="https://private-user-images.githubusercontent.com/99825015/306496344-aab1a6fb-949d-4acf-9229-bab0f56f6b72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDY2MjcsIm5iZiI6MTcwODU0NjMyNywicGF0aCI6Ii85OTgyNTAxNS8zMDY0OTYzNDQtYWFiMWE2ZmItOTQ5ZC00YWNmLTkyMjktYmFiMGY1NmY2YjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDIwMTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiZDhkMTc4YmFkMDY5NGJlNzJmNTQwNzFmZDNkMDFhZTIzOGIzYzA4MTVhNTUwNjNhYmZhYzk2NDA3YzhiN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c6tSakyWjGXSgabVrTuUap-2Zah4bPBsDskGaRBk_GQ">
> and in the frontend this one:
> 
> <img alt="image" width="606" src="https://private-user-images.githubusercontent.com/99825015/306496043-d78498f2-d1dd-48bc-b30c-37f4ee278659.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDY2MjcsIm5iZiI6MTcwODU0NjMyNywicGF0aCI6Ii85OTgyNTAxNS8zMDY0OTYwNDMtZDc4NDk4ZjItZDFkZC00OGJjLWIzMGMtMzdmNGVlMjc4NjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDIwMTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZjgzMzY0MTRiMWI5NzE0YzJhZjMwZjllMWRmZDc4OTRhODdmODE5YmIzYTkwMmE4YWJhOTZkZThiZTcwMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7r-Qf29QYA0JG69YM2viqLEFddRU9mr70yFBdHvjPBg">
> In the screen you can see the crop is ignored
> 
> Below the code used in FE:
> 
> ```
> <img src="{{ glide:immagine_card :crop="crops:freeform:crop" }}"  alt="{{ immagine_card:alt }}"  />
> ```
> 
> Of course I've set the dimension `freeform` in the field section:
> 
> <img alt="image" width="877" src="https://private-user-images.githubusercontent.com/99825015/306496608-d066d5bb-5012-49d8-ad3e-b4dcaaaf8a59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDY2MjcsIm5iZiI6MTcwODU0NjMyNywicGF0aCI6Ii85OTgyNTAxNS8zMDY0OTY2MDgtZDA2NmQ1YmItNTAxMi00OWQ4LWFkM2UtYjRkY2FhYWY4YTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDIwMTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiM2E5MjUwNmViOGUxOWY5M2EzMzQyNDk5Yjk4OGYzMzA5N2E5Njc2ZGY5ZDkzNGM4MDI2ZTU5MGFjNTM5ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oqd9pe9sP-qbYWhAxCIJ_wFByp49JlAvOKf3SzAVZVQ">

I will make a test using the freeform config tomorrow and let you know of the results. 
We don't use the freeform option in our sites, but only fixed dimension keys. Do the 16_9 dimension work for you? 
Could you share the value of the `crops:freeform:crop` with me from the above example?
