### ISSUE TITLE
Addon says update in statamic v4

### ISSUE THREAD

**Issue by AndreasReichl** [tv2regionerne/statamic-image-cropper#8]
The Addon says update to current version but it was already updated!
<img width="967" alt="Bildschirmfoto 2024-02-23 um 12 15 45" src="https://github.com/tv2regionerne/statamic-image-cropper/assets/12985288/b1cad20f-caed-4f7f-9cc0-a90b26cd7581">

**Comment by sylvesterdamgaard** [comment]
I can't see any issues with the semver or package, so not sure why this happens.
I will test on a new install and see if I can replicate the issue.

**Comment by sylvesterdamgaard** [comment]
@AndreasReichl I just tagged a new version 1.5.0. 
Updating to this version seems to solve the issue.

**Comment by AndreasReichl** [comment]
Thanks for the support. Now it works fine!

**Comment by sylvesterdamgaard** [comment]
> Thanks for the support. Now it works fine!

No problem at all. :)
Happy to hear it's resolved for you.
